### ISSUE TITLE
OpenLaw Slack Invite link in docs is no longer valid

### ISSUE THREAD

**Issue by javaadpatel** [openlawteam/docs#160]
Hi, the slack link in the docs:
![image](https://user-images.githubusercontent.com/22832462/67141828-7418a600-f262-11e9-8236-573365c41572.png)

 is no longer valid:
![image](https://user-images.githubusercontent.com/22832462/67141871-7ed33b00-f262-11e9-99cc-26227b8018d5.png)

Is there a new slack link to join the OpenLaw slack?

**Comment by dcol91863** [comment]
I had trouble with this recently as well
