### ISSUE TITLE
Add docs for conversion tool

### ISSUE THREAD

**Issue by outkaj** [openlawteam/docs#25]
+ conversion tool "docs" link should then point to new section on docs site

**Comment by outkaj** [comment]
@fforbeck tagging you over here (feel free to close if not relevant)

**Comment by fforbeck** [comment]
@outkaj what sort of documents we are talking? The code documentation, design etc or about how to use the conversion tool?

**Comment by outkaj** [comment]
Hmm. I think it would be more the latter

**Comment by fforbeck** [comment]
Thanks. I will come up with something and might need your help to review it later.

**Comment by outkaj** [comment]
Sounds good! Would be happy to review.
