### ISSUE TITLE
add video and description for new cross-referencing sections feature

### ISSUE THREAD

**Issue by outkaj** [openlawteam/docs#26]

**Comment by Jdville03** [comment]
@adridadou @craigwblake-openlaw would one of you be able to submit a pr to update the docs for this new feature? the markup language docs will need to be updated to describe this feature with some example code similar to how the rest of the doc is laid out. I also agree that including the video would be nice.

Also, if you made any changes to `Openlaw.scala` or `APIClient.js` those docs will need to be updated too.

**Comment by craigwblake-openlaw** [comment]
Sure, I'll take a look at it.

**Comment by Jdville03** [comment]
@craigwblake-openlaw thanks for helping with the update for this!

**Comment by outkaj** [comment]
can this be closed after @awrigh01 's recent update? or do we still want a video?

**Comment by Jdville03** [comment]
i think we can close for now. there are a couple other somewhat more complex markup language features that would benefit from a video example along with this one. we can open up another issue for that enhancement.
