### ISSUE TITLE
content license

### ISSUE THREAD

**Issue by mroth** [openlawteam/docs#5]
Research and assign a license for our documentation content (or decide upon all rights reserved).

Steps to implement:
- [ ] Add `LICENSE.txt` file to GH repo.
- [ ] Add SPDX identifier for license field to `package.json`.
- [ ] Add section in README noting license and that it applies to content.

**Comment by awrigh01** [comment]
I think we can do a standard CC attribution license here.  See any
commercial concerns?

**Comment by atgrif** [comment]
@awrigh01 Are we looking to keep the documentation strictly non-commercial? I was looking at some examples of CC licenses: https://creativecommons.org/share-your-work/licensing-types-examples/licensing-examples/

**Comment by atgrif** [comment]
We are going to go with the Attribution license: https://creativecommons.org/licenses/by/4.0/ , followed up with Aaron.
