### ISSUE TITLE
update description of Period type once issue-1372 is merged

### ISSUE THREAD

**Issue by outkaj** [openlawteam/docs#57]

**Comment by outkaj** [comment]
I actually don't think anything will need to be changed for this in the docs, based on just looking through. It is just that the output will look different in the text editor. Do you think we need to update the corresponding video(s) accordingly @Jdville03?

**Comment by Jdville03** [comment]
I don't think we need to update the video for that in particular right now. But a project in the new year will be updating all the videos so we can get rid of the outdated ui in all of them.

**Comment by outkaj** [comment]
Sounds good!
